### PR TITLE
feat(pie-docs): add global token usage warning to all global pages

### PR DESCRIPTION
**Pull request by jamieomaguire**
[Added] - a reusable warning about global token usage to all global tokens pages
[Added] - a reusable warning about global token usage to all global tokens pages

### CODE REVIEW

**Comment by jordifornellsJET** [comment]
Hi @jamieomaguire, here are my initial comments:

- I wouldn't capitalise 'Alias Tokens' (let's use 'alias tokens')
- Would it be worth linking to the alias tab for the word 'alias tokens'? Or is it a bit of overkill?

Other than that, it looks great 👍

**Comment by jamieomaguire** [comment]
> Hi @jamieomaguire, here are my initial comments:
> 
> * I wouldn't capitalise 'Alias Tokens' (let's use 'alias tokens')
> * Would it be worth linking to the alias tab for the word 'alias tokens'? Or is it a bit of overkill?
> 
> Other than that, it looks great 👍

Happy to update the spacing, but can you also please do so in Figma? I just copied the text out of the design :) 

Personally, I think the linking is more effort than it's worth but up to you.

**Comment by jordifornellsJET** [comment]
> 

Will update it in Figma 👍, and let's leave this as it is and not include a link. Thanks!
✅ **Design review: Done**

**Review by FayeCarter — DISMISSED** [review]

**Comment by jamieomaguire** [comment]
> > 
> 
> Will update it in Figma 👍, and also can we change the Global Tokens to also not be capitalised? It will read: **Don’t use global tokens directly**. Please make sure you’re using alias tokens in your products.
> 
> Let's leave this as it is and not include a link. Thanks!
> 
> ✅ **Design review: Done**

Thanks @jordifornellsJET, as I mentioned offline I actually think your suggestion would be worth doing as it will improve the mobile UX (prevents having to scroll back up to go to alias). I've just pushed an implementation of this. Please re-review if you can ❤️

**Comment by jordifornellsJET** [comment]
> > > 
> > 
> > 
> > Will update it in Figma 👍, and also can we change the Global Tokens to also not be capitalised? It will read: **Don’t use global tokens directly**. Please make sure you’re using alias tokens in your products.
> > Let's leave this as it is and not include a link. Thanks!
> > ✅ **Design review: Done**
> 
> Thanks @jordifornellsJET, as I mentioned offline I actually think your suggestion would be worth doing as it will improve the mobile UX (prevents having to scroll back up to go to alias). I've just pushed an implementation of this. Please re-review if you can ❤️

Amazing! This looks great, if we could just change the capitalisation on Global Tokens to global tokens, that would be the last bit! Sorry about that, thanks! :)

**Review by jordifornellsJET — APPROVED** [review]

**Review by FayeCarter — APPROVED** [review]

**Review by raoufswe — APPROVED** [review]
image

**Pull request merged**
