### PR TITLE
pie-microsite@v1.45.0 -  Elevation page - Overview tab

### PR DESCRIPTION
**Pull request by raoufswe**
adds Elevation page - Overview tab

### CODE REVIEW

**Comment by jamieomaguire** [comment]
Screenshot 2023-01-24 at 08 55 06

Not sure if designs cover this but do we want to use bold on the token references in the caption?

**Comment by jamieomaguire** [comment]
@raoufswe were you given these SVG images or did you export them yourself? We may not want to use SVG for all of these images (vs compressed jpegs/pngs/webp)

**Review by jamieomaguire — DISMISSED** [review]

**Comment by raoufswe** [comment]
@jamieomaguire I got the assets from Jordi, I do have them in PNG as well, should I change them?

**Comment by raoufswe** [comment]
> Screenshot 2023-01-24 at 08 55 06
> 
> Not sure if designs cover this but do we want to use bold on the token references in the caption?

will be addressed in the future as it will require a bit of changes in figma

**Review by FayeCarter — DISMISSED** [review]

**Review by FayeCarter — APPROVED** [review]

**Review by jamieomaguire — APPROVED** [review]

**Pull request merged**
