### PR TITLE
feat(pie-docs): DSW-870 update radius and elevation global token pages

### PR DESCRIPTION
**Pull request by FayeCarter**
---
"pie-docs": minor
---

[Updated] - elevation and radius global token pages to use `simpleTable` over `tokensTable`

### CODE REVIEW

**Comment by ashleynolan** [comment]
Should the PR title and commit be `pie-docs` rather than `pie-button`?

**Review by raoufswe — APPROVED** [review]

**Review by kevinrodrigues — DISMISSED** [review]

**Review by ashleynolan — CHANGES_REQUESTED** [review]
Just need to update the commit names – happy to help with this

**Review by ashleynolan — DISMISSED** [review]

**Review by nazanin — CHANGES_REQUESTED** [review]
Hey Faye,
I The divider in the pages should not exist, it should be [Title, Text, Notification, Table] with 32px space between Notification and the Table

**Review by nazanin — APPROVED** [review]
Thanks Faye, it looks good

**Review by raoufswe — APPROVED** [review]

**Pull request merged**
