### PR TITLE
feat(generator-pie-component): DSW-000 Add yo prompt package validation

### PR DESCRIPTION
**Pull request by marc-lewis**
## Describe your changes (can list changeset entries if preferable)

https://github.com/user-attachments/assets/96c650b3-3454-4497-94e1-135ab5973b6f

## Author Checklist (complete before requesting a review)
- [x] I have performed a self-review of my code
- [x] I have added thorough tests where applicable (unit / component / visual)
- [x] I have reviewed the `PIE Storybook`/`PIE Docs` PR preview
- [x] If changes will affect consumers of the package, I have created a changeset entry.
- [x] If a changeset file has been created, I have used the `/snapit` functionality to test my changes in a consuming application

### Reviewer 1 @raoufswe 
- [x] I tested locally 

### Reviewer 2 @siggerzz 
- [x] I tested locally

### CODE REVIEW

**Comment by marc-lewis** [comment]
Draft until I can figure out how to yo prompts/generator.

**Review by siggerzz — APPROVED** [review]

**Comment by siggerzz** [comment]
@marc-lewis You should be able to do the following:

From the root of the repo - `yarn build --filter=generator-pie-component`

Then link your local version of the package via:

```
cd ./packages/tools/generator-pie-component
npm link
```

Once this is done, running the `yo @justeattakeaway/pie-component` _should_ use your local version! 👍🏼

**Comment by siggerzz** [comment]
Tested locally and works as expected 👍🏼

**Review by raoufswe — APPROVED** [review]

**Pull request merged**
