### PR TITLE
feat(pie-icons): DSW-769 icon updates

### PR DESCRIPTION
**Pull request by xander-marjoram**
### Dietary
- celery
- crustaceans
- fish
- lupin
- sesame-seeds
- soybeans
- sulphites

### Functionality
- image-flip-horizontal
- image-flip-vertical

### Misc
- bakery
- beauty
- books
- cleaning
- clothing
- diy
- electronic-accessories
- fresh-food
- gifts
- pet-supplies-alt
- pharmacy-alt
- shops
- stationery
- toys-games

### Pay
- account-credit
- instant-bank
- unpaid

### Restaurant
- collect
- management
- prepare-bag

### Payment methods (`/payment` folder)
- abn-amro
- affirm
- ali-pay
- amazon
- amex
- bancontact (new name for mister-cash, which will be removed later)
- bit-pay
- bitcoin-cash
- citadele
- diners-club
- discover
- elo
- etherium
- forbrugsforeningen
- ing
- interac
- jcb
- litecoin
- maestro
- mastercard
- payoneer
- paysafe
- qiwi
- sepa
- shop-pay
- skrill
- stripe
- union-pay
- verifone
- visa
- web-money
- we-chat
- yandex

## [Changed] - updated icons

Note that some updates may be very small.

### Dietary
- eggs

### Functionality
- check-circle
- check-circle-filled

### Stampcard
- stampcard-10
- stampcard-10-filled

### Payment
- apple-pay
- bitcoin
- eps
- google-pay
- giropay
- i-deal
- klarna
- mister-cash
- mobile-pay
- paypal
- payu
- post-finance
- sodexo
- sofort
- twint
- vvv

### Social (`/social` folder)
- google-static

## Author Checklist (complete before requesting a review)
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests
- [ ] If it is a `PIE Docs` change, I have reviewed the Docs site preview
- [ ] If it is a component change, I have reviewed the Storybook preview
- [ ] If there are visual test updates, I have reviewed them properly before approving

### Reviewer 1
- [ ] If it is a `PIE Docs` change, I have reviewed the PR preview
- [ ] If there are visual test updates, I have reviewed them

### Reviewer 2
- [ ] If it is a `PIE Docs` change, I have reviewed the PR preview
- [ ] If there are visual test updates, I have reviewed them

### CODE REVIEW

**Review by raoufswe — APPROVED** [review]

**Review by dandel10n — COMMENTED** [review]
Looks good!
I have few questions just to confirm:

1. Have you checked that added/updated icons render correctly? There were issues in the past with the svg structure that didn't allow mono coloured icons to render as expected.
2. I think the changeset should contain vue, react and webc icon packages as they should be released automatically in this case and it will be more visible what changed/added if they have changelog for these changes. But I am not 100% sure.

**Comment by xander-marjoram** [comment]
The visual regression screenshots look good to me, apart from a couple of images which contain the old `check-circle` icon so I've asked design if these need to be updated too.

**Comment by dandel10n** [comment]
> The visual regression screenshots look good to me, apart from a couple of images which contain the old `check-circle` icon so I've asked design if these need to be updated too.

Yes, I scrolled through the percy screenshot but icons are so tiny that I couldn't see if they rendered as expected

**Comment by xander-marjoram** [comment]
@dandel10n I wasn't expecting an update to the Vue/React/WebC packages as part of this PR, because the generated icon files are no longer in source control.

I _think_ the next versioning PR should cover that by bumping the pie-icons version, publishing it and then using that version in the other packages. If you think it will work differently it would be great to have a chat to work it out.

**Review by fernandofranca — DISMISSED** [review]

**Review by dandel10n — APPROVED** [review]

**Review by raoufswe — APPROVED** [review]

**Review by fernandofranca — APPROVED** [review]

**Pull request merged**
